### ISSUE TITLE
Saved samples directory structure

### ISSUE THREAD

**Issue by faildeny** [RichardObi/medigan#37]
## What directory structure would be best for saved samples?
Currently I see two options:
### First: Everything in one directory, that's simple to implement.
```
-- output_path
    0_img.png
    0_mask.png
    1_img.png
    ...
```
### Second: Samples grouped by type.
```
-- output_path
    -- img
        0_img.png
        1_img.png
    -- mask
        0_mask.png
        ...
```
I have a particular case for FID calculation, where the user provides path to image directory. With the first approach this will involve some additional work and file preprocessing. To have the second approach, `medigan` guidelines will have to be updated, to require contributors to save each type of output data in separate directory. However, any additional sample use like statistics calculation will be very straightforward.
The first approach is already implemented in #36

**Comment by RichardObi** [comment]
Hmm.. good point. A potential solution could be [this one](https://github.com/RichardObi/medigan/pull/36#issuecomment-1222262224)
