### ISSUE TITLE
Can I use this weights as pretrained model to transfer my task ? 

### ISSUE THREAD

**Issue by xiaoerlaigeid** [RichardObi/medigan#60]
Thanks for your work  ! I wonder if there offer a code script that can used for transfer learning on my own dataset. If not I am very glad to contribute to this 
Best

**Comment by RichardObi** [comment]
Hi @xiaoerlaigeid, maybe we can provide the training script. Which of the models in medigan would you like to use?

**Comment by RichardObi** [comment]
> Thanks for your reply. I may try two types of models.
> 
> 1. I attempt to train a DCGAN (256x256 or 512x512 image size). I may need to modify some layers.
> 2. Another model is C-DCGAN.

Nice! You may check out the [training code](https://github.com/zuzaanto/mammo_gans/blob/main/gan_compare/scripts/train_gan.py) for DCGAN and C-DCGAN (128x128 or 224x224) that we have in [this repo](https://github.com/zuzaanto/mammo_gans).

**Comment by RichardObi** [comment]
> @RichardObi Another question regarding to your paper "High-resolution synthesis of high-density breast mammograms: Application to improved fairness in deep learning based mass detection" How you generated the annotation bounding box ? Manually annotated or generated by Cyclegan ?

In this [work](https://www.frontiersin.org/articles/10.3389/fonc.2022.1044496/full) we translated low density breast to high density breast mammograms with cycleGAN. The masses were annotated as bounding box in the source domain (e.g. low density breast). We used the same source domain bounding boxes as annotations in the target domain (after cycleGAN translation).

**Comment by RichardObi** [comment]
> Thanks a lot! It seems that link I cannot open https://github.com/zuzaanto/mammo_gans/blob/main/gan_compare/scripts/train_gan.py

Sorry, here the [link](https://github.com/zuzaanto/mammo_gans_iwbi2022/blob/main/gan_compare/scripts/train_gan.py) to the public repository.

**Comment by RichardObi** [comment]
Hi @xiaoerlaigeid. Yes, the whole breast image is processed in order to translate the breast density. The default output pixel dimension is 1332x800, but you can also pass another `image_size=[1332, 800]` to change the rescaling of your input image before translation (see [here](https://medigan.readthedocs.io/en/latest/models.html#cyclegan-mmg-density-full))
