### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by mckellwoodland** [RichardObi/medigan#61]
Hello,

It looks like the link to the Google Drive that contains the InceptionV3 weights on RadImageNet is broken, making the calculation of the FID with these weights incalculable.

McKell

**Comment by RichardObi** [comment]
Hi @mckellwoodland, thank you for bringing this to our attention. We are happy that the FID computation with RadImageNet is useful and updated the link to the InceptionV3 weights in [fid.py](https://github.com/RichardObi/medigan/blob/main/tests/fid.py).
