### ISSUE TITLE
Union package unavailable

### ISSUE THREAD

**Issue by darioguidotti** [RichardObi/medigan#69]
Dear Richard,

I have recently attempted to generate sample data using `00016_CYCLEGAN_MMG_DENSITY_CSAW_CC` and `00015_CYCLEGAN_MMG_DENSITY_CSAW_MLO`. Regrettably, it appears that the Union package, which is apparently a dependency of these models, has been removed from pip in all versions and is therefore unavailable. 

Is there an alternative solution you can suggest?

Kind regards,
Dario

**Comment by BYALPERENK** [comment]
I have same problem. I tried many things but no solution

**Comment by BYALPERENK** [comment]
I created new env "python==3.7" and i installed "pip install union==0.1.10"
When i run my code 
Generators().generate(
    model_id="00003_CYCLEGAN_MMG_DENSITY_FULL",
    input_path="models/00003_CYCLEGAN_MMG_DENSITY_FULL/images",
    image_size=[1332, 800],
    gpu_id=0,
    install_dependencies=True,
)
with "install_dependencies=True" it installed other dependencies. This worked for me.

**Comment by darioguidotti** [comment]
I managed to make it work by removing the package requirement from the configuration file: it does not seem to be needed to run the models.

**Comment by RichardObi** [comment]
Hi @darioguidotti @BYALPERENK, thank you very much for pointing out this issue and even solving it already!! 👏

I tested the issue and found that indeed the required `Union` package is unused in the model code for models `00003_CYCLEGAN_MMG_DENSITY_FULL`, `00004_PIX2PIX_MMG_MASSES_W_MASKS`, `00013_CYCLEGAN_MMG_DENSITY_OPTIMAM_MLO`, `00014_CYCLEGAN_MMG_DENSITY_OPTIMAM_CC`, `00015_CYCLEGAN_MMG_DENSITY_CSAW_MLO`, `00016_CYCLEGAN_MMG_DENSITY_CSAW_CC`. 

I removed the `Union` package requirement in the [global.json](https://github.com/RichardObi/medigan/blob/main/config/global.json) file, which should solve this issue after merging the [PR](https://github.com/RichardObi/medigan/pull/70).
